name: pconbr

channels:
  - conda-forge
  - bioconda

dependencies:
  - jupyterlab=1.1
  - nb_conda=2.2
  - snakemake=5.7
  - seqtk=1.3
  - n50=0.83
  - kmc=3.1
  - jellyfish=2.2
  - minimap2=2.17
  - samtools=1.9
  - elector>=1.0.2
  -pip=3
  - pip:
    - "git+https://github.com/rrwick/Badread.git"