name: pconbr

channels:
  - conda-forge
  - bioconda

dependencies:
  - jupyterlab=2.1.5
  - nb_conda=2.2
  - snakemake=5.19
  - seqtk=1.3
  - n50=1.3
  - kmc=3.1
  - jellyfish=2.2
  - minimap2=2.17
  - samtools=1.10
  - pip=3
  - pip:
    - "git+https://github.com/rrwick/Badread.git"
